### ISSUE TITLE
Help with installation and usage

### ISSUE THREAD

**Issue by pikim** [wernerjoss/grav-plugin-fullcalendar#1]
Hello Werner,

I'm trying to use this plugin in Grav. I was not able to install it via `bin/gpm install fullcalendar` and therefore had to install it manually. Now I'm not sure how to use it. I took your example, modified it to `[fullcalendar icsfile=termine.ics]test[/fullcalendar]` and put that into a markdown file. The file `user/data/calendars/termine.ics` does exist, but I can only see the text `[fullcalendar icsfile=termine.ics]test[/fullcalendar]` on my rendered page.

Best regards
Michael

**Comment by wernerjoss** [comment]
Hi Michael,
sorry for the late answer - I didn't look into issues for quite a while :)
- you should have installed [shortcode core](https://github.com/getgrav/grav-plugin-shortcode-core) - if not, just do it and try again !

**Comment by pikim** [comment]
Hi Werner,
thanks for your answer and sorry for my late reply.

In the meantime I installed Fullcalendar via the Grav plugins section and it automatically installed Shortcode Core.

Now I can see the calendar on my page, but it doesn't show any event. I tried different ics-files, but the result is always the same.

All of my calendars were created with Thunderbird/Lightning, could this be a problem?

Best regards
Michael

**Comment by wernerjoss** [comment]
Hi Michael,
can you provide such an ics file ?
e.g. by uploading to [pastebin](https://pastebin.com) ?
additionally, you can inspect what is going on in your browser's debug mode (on windoze, hit F12, then look into console output) after changing $verbose to true in file user/plugins/fullcalendar/templates/partials/fullcalendar.html.twig

**Comment by pikim** [comment]
Hi Werner,

I just created an example file:
[ztest.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/3462858/ztest.zip)

I also tried to inspect what happens as you described, but I didn't figure out how to see anything useful there.

**Comment by wernerjoss** [comment]
Hi Michael,
your test file is ok, it works here, has 3 events test1..test3 in August.
also validates in [validator](https://icalendar.org/validator.html).
did you save it in user/data/calendars ?
and then add it as described via shortcode [fullcalendar icsfile=ztest.ics][/fullcalendar] ?
did you change the $verbose flag to true ?

**Comment by pikim** [comment]
> did you save it in user/data/calendars ?
> and then add it as described via shortcode [fullcalendar icsfile=ztest.ics][/fullcalendar] ?
> did you change the $verbose flag to true ?

Yes, yes and yes.

**Comment by wernerjoss** [comment]
ok, then, as already stated, you should open your browser's developer tools, see
[this](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools) guide for firefox (other browsers have similar tools).
then look in the javascript console.
with the $verbose flag enabled, you will clearly see if your calendar file is found and if it works.
![Screenshot_20190804_072916](https://user-images.githubusercontent.com/36265757/62419890-99960a80-b68a-11e9-99d5-021601845124.png)

**Comment by pikim** [comment]
OK, I see. It looks like on the following screenshot:
![Screenshot_20190804_085300](https://user-images.githubusercontent.com/11775849/62420645-11b5fd80-b696-11e9-9a23-a58c0db91eba.png)

**Comment by wernerjoss** [comment]
so the ics file is found.
what does the console window show when you scroll further down ?
(the allevents array display is of interest, because that holds the recognized events from the calendar)

**Comment by wernerjoss** [comment]
ok, I think I found the problem:
can you disable "include default language" in your dashboard and try again ?

**Comment by pikim** [comment]
It is disabled, see
![Screenshot_20190804_102256](https://user-images.githubusercontent.com/11775849/62421437-fea92a80-b6a1-11e9-8422-2df13a93b797.png)

**Comment by wernerjoss** [comment]
does it work now ?
if not, how does the javascript console output look like ?
(maybe you also need to clear the cache to take effect)

**Comment by pikim** [comment]
It was disabled all the time, so nothing has changed.

**Comment by wernerjoss** [comment]
hm,
strange. As stated above, I found a problem with the ics file URL evaluation in case "include default language" is enabled - no problem if disabled, though.
can you try to specify the complete absolute URL to your ics file (e.g. "http://mysite.de/grav/user/data/calendars/ztest.ics"), including the surroundig " " in your shortcode ?
(make sure the browser finds that file if you put it directly in the address field)

**Comment by pikim** [comment]
The result is the same with the absolute URL, although the debug output is a bit different. Especially the calendar URL looks very strange.
![Screenshot_20190804_212421](https://user-images.githubusercontent.com/11775849/62428157-a6544600-b6fe-11e9-9561-edf418c0df98.png)

**Comment by wernerjoss** [comment]
the calendar url looks strange, yes.
seems to be duplicated, somehow.
can you send me the shortcode with full URL via email to expires190731 AT hoernerfranzracing.de ?

**Comment by pikim** [comment]
I sent you an email right now.

**Comment by GogoFC** [comment]
oh nooo you guys continued this conversation privately :) .
I was trying to figure out how to set parameters in short code from this text "Once installed and enabled, you can use this Plugin to parse an ICS Calendar File (must be found in user/data/calendars and set as parameter in Plugin shortcode, without Path !)"

Without doing anything to shortcode I had an empty calendar on page with error 404, then I edited file shortcode-core.yaml cuz you know :), i've only been with Grav for 3 days now :) don't know what I'm doing, I added the line [fullcalendar icsfile=calendartest.ics][/fullcalendar] at the end because after custom shortcodes it changed color :). So now I get error 500.  

Did not read README in short code, but will now, I was hoping to copy pikim's shortcode edit, but I only copied his ics file :) ..

If you guys can help, please do, calendar looks awesome on white background

-- I am still on 404 (Not Found) stage :)

Edit:  :) well, pikim now your calendar is all over my page :) 

![Screenshot from 2019-10-04 07-34-36](https://user-images.githubusercontent.com/9360410/66208455-b6df5900-e67a-11e9-93e6-892e20d13350.png)
This happened after I changed the verbose variable back to false to see what would happen, following clues from up there :). So now i had to delete the ics file, it's on every one of my pages including admin login page .
Also I added a custom shortcode path to the ics file instead of shortcode php file :) so I broke it :) ...
I will wait for you guys before I start breaking stuff again.

**Comment by pikim** [comment]
> oh nooo you guys continued this conversation privately :) .

Yes, but I only sent Werner the link to my calendar, nothing else. But this also means that we didn't find a solution. Therefore I adjusted the already existing Events plugin from Kaleb Heitzman so that it reads one or more ics files and creates pages from the events and display them in calendar or list style. Meanwhile 'my' version has replaced the original version so that you can install it directly from within Grav.

**Comment by GogoFC** [comment]
ooO thanks :) .. i'm gonna try that plugin events also, but i also wanted tfullcalendar because it looks good :) ... can i see what yours looks like now with events plugin.

and regarding fullcalendar, i didn't know what needed to be done about shortcode at all, i read shortcode readme, still don't :) , i'm just beginning

**Comment by wernerjoss** [comment]
closing this issue now since there have been no further comments in quite some time.
if there are still issues with the current/next version (see also #8 ), please open new issue.

**Comment by pikim** [comment]
@GogoAkira 
You asked how the Events calendar is looking like and to complete this topic:

![grafik](https://user-images.githubusercontent.com/11775849/71812088-99a19880-3076-11ea-980b-48a4a6a5b821.png)
