### ISSUE TITLE
Repeating events

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#10]
I found a solution for repeating events with .ics calendar.  
instead of Google I use now Yandex.com calendar and tried it with a CORS proxy:  
``"https://cors-anywhere.herokuapp.com/https://calendar.yandex.com/export/ics.xml?private_token=xxxxxxxxxxxxxxxx&tz_id=Europe/Madrid"``  
 but I don't choose *repeating event* only start and end time.
I think with Yandex it is possible to import a Google calendar.

test page https://tim-hs.site/ths/de/sample-page

**Comment by wernerjoss** [comment]
ok, I see - but the test page only shows consecutive events for several days (all days between start and end day included) which is of course no problem.
anyways, meanwhile, I have done some more investigation on fullcalendar.io on repeating events.
from V 4.3, there have been many improvements, including a reccuring events plugin which was not available for V 3.x (the version my Grav Plugin is based on).
I'm planning to update to V 4.3 in the future, and also check if the recurring events plugin can be incorporated without much headache, so stay tuned  :)

**Comment by fugo** [comment]
> but the test page only shows consecutive events for several days (all days between start and end day included)

I will need this for a kind of booking calendar to show available/unavailable days.
Also overlapping is possible and controlling with my mobile (a+ calendar app)
Right now I'm quite satisfied with your plugin -than you. :smirk:

**Comment by wernerjoss** [comment]
there is a new Version (0.2.0) in trunk, which supports recurring events - see the docs (README.md).
But, as this is a major rewrite, also based on fullcalendar.io V 4.3.1 instead of 3.1, I have not yet created a release which will be distributed via the Grav Plugin updater, but rather would like to have this tested and confirmed working as expected by interested users.
Doing this is rather easy:

1. delete ALL files and directories in your user/plugins/fullcalendar folder (you can also uninstall the plugin, but that will also remove the fullcalendar folder, which will have to be recreated afterwards)
2. download the zip file for the current development version from here, unpack it somewhere on your computer
3. copy all files and folders from the unpacked archive to your user/plugins/fullcalendar folder
4. evtl. make Adaptions (locale: xx) to your user/config/plugins/fullcalendar.yaml file
5. clear cache

If anything goes wrong, you can always just delete your user/plugins/fullcalendar folder and then re-install to previous Version (0.1.5)
As always, comments, requests and patches are welcome :)

**Comment by wernerjoss** [comment]
> Right now I'm quite satisfied with your plugin -than you. smirk

ok, if you like it, you can give it a star :smile:

**Comment by fugo** [comment]
> ok, if you like it, you can give it a star smile
Sorry I forgot 
I installed the new version 0.2.0 - first impression :+1:  the new CSS styling is very fine.
Repeating days is working 50/50 :smile: 
I have a event on every Wednesday/Friday/Saturday on 10 to 12am from 8th Jan to 6th of March but only the events on Wednesday show up. Before I tried full day but its the same.

**Comment by wernerjoss** [comment]
ok, 50/50 is better than 0/100 :smiley: 
can you post your complete RRULE: line from your ics file here ?
or (better) the whole BEGIN:VEVENT ... END:VEVENT part ?

**Comment by fugo** [comment]
[source_code_html_calendar_page.txt](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/4032372/source_code_html_calendar_page.txt)
from ics-file:

```ics
BEGIN:VEVENT
DTSTART;TZID=Europe/Madrid:20200101T100000
DTEND;TZID=Europe/Madrid:20200101T120000
SUMMARY:Termin mehrfach MI-FR-SA
UID:tiFjWb14yandex.ru
SEQUENCE:1
DTSTAMP:20200107T202551Z
CREATED:20200107T183415Z
URL:https://calendar.yandex.com/event?event_id=1275728714
RRULE:FREQ=WEEKLY;BYDAY=WE,FR,SA;UNTIL=20200306T100000Z;INTERVAL=1
TRANSP:OPAQUE
CATEGORIES:Test
LAST-MODIFIED:20200107T183920Z
END:VEVENT
```

**Comment by wernerjoss** [comment]
ok, I found and fixed the error 😄 
can you try the updated version ?
(the only file to be replaced is templates/partials/fullcalendar.html.twig)
... and don't forget to clear the cache ...

**Comment by fugo** [comment]
It works 100% :smiley: :+1: 
I also tried Google Calendar on other page and it also works.
Thank you a lot! Think we can close this issue? :smirk: 
Only one question - with Yandex calendar I can click on an event and this links to my Yandex calendar (feature or bug?).
With Google this don't work. I don't need this, only curious  about it
https://tim-hs.site/ths/de/kalender (Google Cal.)

**Comment by wernerjoss** [comment]
Ok, fine - I'm closing this now as resolved, will also create a new release which will then be pulled automatically by Grav gpm.
As for your question, this is entirely dependent on your Calendar Implementation.
As you can see from the ics source you provided, there is an URL: line in your ics file.
That is then used by fullcalendar as a link when you click on an event.
Google just does not add an URL: line by itself (must be defined by the event author explicitely).
