### ISSUE TITLE
iCal Rendering Incorrect Events

### ISSUE THREAD

**Issue by thekenshow** [wernerjoss/grav-plugin-fullcalendar#25]
I have a Gmail calendar being pulled into FullCalendar as follows:

```
[fullcalendar icsfile="https://calendar.google.com/calendar/ical/mail%40harmonycentreos.ca/public/basic.ics"][/fullcalendar]
```
Using the October 5th, 2020 box in the image below:

![Screen Shot 2020-10-27 at 11 50 31 AM](https://user-images.githubusercontent.com/998832/97327401-4e49b800-184b-11eb-8e1f-281b1855ea78.png)

There are two errors:

-  The **9:30p Auditorium - GBCC** event is supposed to appear at 5:30p. 
- The **10p Common - Nihon Karate** event does not exist; possibly a duplicate of the correctly placed **6p Commons - Nihon Karate** event?

In my shared Gmail Calendar, and when I download that .ics file and load it into macOS Calendar, the "Auditorium - GBCC" event time is correct and there is no second "Common - Nihon Karate" event.

**Google Calendar**

![Screen Shot 2020-10-27 at 11 56 58 AM](https://user-images.githubusercontent.com/998832/97327772-af718b80-184b-11eb-9817-59fa73e8fe73.png)

**macOS Calendar**

![Screen Shot 2020-10-27 at 11 50 07 AM](https://user-images.githubusercontent.com/998832/97327775-b0a2b880-184b-11eb-8dc9-8afa8dac576b.png)

What would account for this?

**Comment by wernerjoss** [comment]
Hi @thekenshow - 1st, sorry for my late answer,
I had not looked into the issues for this project for quite some time (unfortunately, there is no automatic notification per email when a new issue is created, only for answers on already existing ones).
but, back to the issue: 
this is most likely due to the still unresolved handling of EXDATE Rules within recurring events, see issue #18 .
as stated there, there is already a Plugin which can handle that by @sherpadawan - see [here](https://github.com/sherpadawan/grav-plugin-fullcalendar).
If you don't need more than one calendar to display, you can just use that.
I'm currently investigating if these 2 plugins can be combined, but no guarantee, how long that will take.

**Comment by wernerjoss** [comment]
additional note: the time offset problem for recurring events (only those are effected) can be worked around with a config variable tz_offset (2 in this case) - see already closed issue #21 .
the other issue with EXDATE not working hovever, still can not be taken into account, except with changed rrules (not working with EXDATE/EXRULES).

**Comment by thekenshow** [comment]
Thanks for the response - I've had to back off and use embedded Google calendars (agenda view) in order to launch the site. Not ideal, but my non-profit client really needed the new site and it was good enough for now. It's looking like a full calendar will not be needed; instead, something like your iCalendar plugin that can read a remote .ics.

**Comment by wernerjoss** [comment]
ok, fine to see you got it sorted out for now.
I'm closing this now, as timezone and exceptions for recurring events will probably not be fixed in this version, see my comments above.
