### ISSUE TITLE
Calendar not shown / no js files present

### ISSUE THREAD

**Issue by makrohard** [wernerjoss/grav-plugin-fullcalendar#32]
I can't get fullcalendar to work using the Open Publishing Space Skeletton. I installed the fullcalender-plugin using the admin plugin and invoke it like so: [fullcalendar icsfile="file.ics"][/fullcalendar]. The calender does not show up as expected.

The generated page does contain empty <div's>,  but I couldn't see any client-sided scripts using the dev-tools in the browser. I expected to see calandar.js and some other scripts, but they do not seem to be present.

I did not find any logfile-entries either. Any ideas on how to get it working?

**Comment by wernerjoss** [comment]
this plugins needs jquery to be loaded, most themes do this, I guess yours does not.
try setting addJquery to true (1) in the plugin configuration.
(I just looked at [quark open publishing](https://github.com/hibbitts-design/grav-theme-quark-open-publishing) - if this is what you are referring to, you can ignore this hint, as it does load jquery).

in any case, be sure to use the calendar template for your calendar page, otherwise it will not work.

**Comment by makrohard** [comment]
At the very moment one does it right: It works just fine. I did not use the calendar template. Thanks for helping!
