### ISSUE TITLE
In which file can I translate "today" ?

### ISSUE THREAD

**Issue by ventoux84** [wernerjoss/grav-plugin-fullcalendar#55]
Hello,
My site is in french, but the calendar's page shows a button with "Today"; even if the names of the months are in French.
https://ibb.co/8YwZJ6z
In which file can I translate this word ? 

I saw that in locales-all.min.js and locales-all.js today is translated in french as "Aujourd'hui"
.
Can you tell me where this other "Today" is that is displayed at the top of the calendar?

**Comment by wernerjoss** [comment]
well, you are right, same here :smile: ('Today' should be 'Heute' in german...).
but, does not seem to be so easy to fix, as, the correct translations are in the locale files, but somehow not picked up despite the locale variable (=language) is correctly set.
I'll look into this later, as I don't have much time currently.
as a workaround, you can edit the file assets/calendar.js, go to line 199 (which is 'navlinks: false) and add the following code just before that line:
`
buttonText: {
            today: "Aujourd'hui"
},
`
that should work - of course this is not a real solution, just an ugly hack :grin:

**Comment by wernerjoss** [comment]
well, this ugly hack is really bad - there is now a primitive fix in calendar.js which should work at least for some common languages (german, french, italian, spanish) - please just replace this file and check if it works for you.

**Comment by ventoux84** [comment]
Tanks for this fix, but with the new calendar.js, nothing is displayed; only the  page's title.
I forget something ?

With the ugly hack, the one who is really bad, it works well !!!
Sometime, i love ugly thing.

**Comment by wernerjoss** [comment]
that sounds strange,
the changes are nowhere so that they could affect data loading/display.
you can see the fixed version running on my own calendar:
https://hoernerfranzracing.de/werner/kalender[1]

did you enable console logging (verbose=true) and check if your calendar files are 
found ?

Am Montag, 31. Juli 2023, 07:45:14 CEST schrieb ventoux84:
> Tanks for this fix, but with the new calendar.js, nothing is displayed; only
> the  page's title. I forget something ?



--------
[1] https://hoernerfranzracing.de/werner/kalender

**Comment by ventoux84** [comment]
I will investigate this afternoon in my site.

**Comment by wernerjoss** [comment]
Am Montag, 31. Juli 2023, 09:09:18 CEST schrieb ventoux84:
> ERROR :-(
> Uuups. Sieht aus als ob diese Seite nicht existiert.

ok, the link was mangled by email response :-)
just select 'Kalender' from the left sidebar navigation.

**Comment by ventoux84** [comment]
Yes, i saw too late and edited my post, but you are very fast !

**Comment by ventoux84** [comment]
Yes, i saw too late and edited my post, but you are very fast !
Instead of downloading the file from Github, I copied its contents onto the old one.
This way, it works fine.

I thank you very much for your work and wish you a wonderful summer.
If you're ever in my area, please let me know. I'd love to have a beer with you.

**Comment by wernerjoss** [comment]
Am Montag, 31. Juli 2023, 15:10:15 CEST schrieb ventoux84:
> Yes, i saw too late and edited my post, but you are very fast !
> Instead of downloading the file from Github, I copied its contents onto the
> old one. This way, it works fine.

ok, fine, that is what I expected - I could not imagine why it would not work 
for you.
however, I will not create a new release ATM, as the current workaround is not 
elegant, I also have some other plans on my schedule, but that will take some 
time.
so, just keep the development version for the time beeing.

> I thank you very much for your work and wish you a wonderful summer.
> If you're ever in my area, please let me know. I'd love to have a beer with
> you.

that is a good proposal :-)
I haven't been in this area since 2017, but I will surely come back at some 
time in the future.
if you like, you can contact me directly on my website (page Impressum - 
elektronische Post) - this way I can store your email address and contact you 
once I'll be there.
cu
Werner
