### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rkl110** [wernerjoss/grav-plugin-fullcalendar#7]
Hey,
I just thought it would be great to set a color for each ical file.
Like:
Dates in ical file 1 = red
Dates in ical file 2 = blue

**Comment by wernerjoss** [comment]
I already looked into this because I could use this feature also for myself :-)
however, it turned out to not beeing that easy.
I'll have to figure out how to specify mutliple event source functions (standard is only one which collects all events into one array which has a single color).
I'll postpone this for later when I find more time to work on it...

**Comment by wernerjoss** [comment]
Done with release 0.1.5 - enjoy :D
